UNK_ACTION = 'UNK'
STATE_CLA = '[state]'
CONTEXT_CLA = '[context]'
USER = '[user]'
DATABASE = '[database]'
DATABASE_COUNTS = '[database]'
CONTEXT_SEP = '. '
STATE_GEN = '[state]'
CONTEXT_GEN = '[context]'
USER_GEN = '[user]'
DATABASE_COUNTS_GEN = '[database]'
TASK_DESCRIPTION_STATE_UPDATE = 'Update state:'
TASK_DESCRIPTION_ACTION_GENERATION = 'Generate actions:'
SPECIAL_TOKENS = [STATE_CLA, DATABASE, DATABASE_COUNTS, CONTEXT_CLA, USER]
DOMAIN_NAMES = sorted({'hotel', 'restaurant', 'bus', 'train', 'attraction', 'hospital', 'taxi'})
OUTPUT_DF_COLUMNS = ['text', 'actions', 'predicted', 'dialogue_acts', 'system_utterance', 'scores']
COMMON_SLOTS = ["intent", "requested"]
DOMAIN_SLOTS = dict(bus=COMMON_SLOTS + sorted(["day", "departure", "destination", "leaveat"]),
                    hotel=COMMON_SLOTS + sorted(
                        ["area", "bookday", "bookpeople", "bookstay", "internet", "name", "parking",
                         "pricerange", "stars", "type"]),
                    restaurant=COMMON_SLOTS + sorted(
                        ["area", "bookday", "bookpeople", "booktime", "food", "name", "pricerange"]),
                    train=COMMON_SLOTS + sorted(
                        ["arriveby", "bookpeople", "day", "departure", "destination", "leaveat"]),
                    attraction=COMMON_SLOTS + sorted(["area", "name", "type"]),
                    hospital=COMMON_SLOTS + ["department"],
                    taxi=COMMON_SLOTS + sorted(["arriveby", "departure", "destination", "leaveat"]))

UNIQUE_ACTIONS = [
    'general-reqmore',
    'general-bye',
    'booking-inform',
    'booking-book(ref)',
    'general-welcome',
    'restaurant-inform(name)',
    'hotel-inform(choice)',
    'train-inform(leaveat)',
    'hotel-inform(name)',
    'restaurant-inform(choice)',
    'train-inform(trainid)',
    'restaurant-inform(food)',
    'restaurant-inform(area)',
    'hotel-inform(type)',
    'train-inform(arriveby)',
    'train-offerbook',
    'attraction-inform(name)',
    'restaurant-inform(pricerange)',
    'hotel-inform(area)',
    'hotel-inform(pricerange)',
    'attraction-inform(area)',
    'hotel-request(area)',
    'attraction-inform(choice)',
    'general-greet',
    'train-offerbooked(ref)',
    'restaurant-inform(address)',
    'train-inform(choice)',
    'attraction-inform(address)',
    'taxi-inform(type)',
    'attraction-inform(type)',
    'taxi-inform(phone)',
    'attraction-inform(phone)',
    'train-request(leaveat)',
    'attraction-inform(entrancefee)',
    'restaurant-request(food)',
    'hotel-inform(stars)',
    'attraction-inform(phone)',
    'booking-request(bookday)',
    'hotel-recommend(name)',
    'train-inform(destination)',
    'attraction-inform(postcode)',
    'restaurant-inform(phone)',
    'restaurant-recommend(name)',
    'train-request(departure)',
    'train-request(day)',
    'hotel-inform(internet)',
    'attraction-recommend(name)',
    'train-request(destination)',
    'hotel-inform(parking)',
    'booking-book(name)',
    'train-inform(departure)',
    'hotel-request(pricerange)',
    'train-offerbooked(price)',
    'train-inform(price)',
    'booking-nobook',
    'restaurant-request(area)',
    'hotel-inform(address)',
    'booking-request(bookpeople)',
    'train-request(arriveby)',
    'booking-book(bookday)',
    'train-inform(day)',
    'restaurant-inform(postcode)',
    'train-inform(duration)',
    'booking-request(booktime)',
    'booking-request(bookstay)',
    'restaurant-request(pricerange)',
    'attraction-request(type)',
    'restaurant-nooffer',
    'booking-book(bookpeople)',
    'attraction-request(area)',
    'taxi-request(leaveat)',
    'taxi-request(departure)',
    'hotel-inform(phone)',
    'restaurant-nooffer(food)',
    'hotel-inform(postcode)',
    'booking-book(booktime)',
    'train-request(bookpeople)',
    'hotel-select',
    'taxi-request(destination)',
    'restaurant-select',
    'booking-book(bookstay)',
    'hotel-nooffer(type)',
    'train-offerbooked(trainid)',
    'hotel-recommend(area)',
    'attraction-recommend(entrancefee)',
    'taxi-request(arriveby)',
    'attraction-recommend(address)',
    'hotel-request(stars)',
    'train-offerbooked(bookpeople)',
    'restaurant-recommend(food)',
    'hotel-nooffer',
    'restaurant-recommend(area)',
    'restaurant-nooffer(area)',
    'hospital-inform(address)',
    'attraction-recommend(area)',
    'hotel-recommend(pricerange)',
    'attraction-nooffer(area)',
    'attraction-nooffer(type)',
    'hospital-inform(phone)',
    'hospital-inform(postcode)',
    'hotel-recommend(stars)',
    'restaurant-recommend(pricerange)',
    'police-inform(phone)',
    'hospital-inform(name)',
    'booking-inform(name)',
    'train-select',
    'hotel-select(type)',
    'police-inform(postcode)',
    'hotel-request(parking)',
    'hotel-request(type)',
    'police-inform(address)',
    'attraction-select',
    'hotel-nooffer(area)',
    'hotel-nooffer(stars)',
    'train-offerbooked(leaveat)',
    'taxi-inform(departure)',
    'restaurant-recommend(address)',
    'restaurant-select(food)',
    'hotel-nooffer(pricerange)',
    'attraction-recommend(type)',
    'hotel-request(internet)',
    'hotel-recommend(type)',
    'hotel-recommend(internet)',
    'taxi-inform(destination)',
    'taxi-inform(leaveat)',
    'train-offerbook(trainid)',
    'restaurant-nooffer(pricerange)',
    'hotel-recommend(parking)',
    'attraction-recommend(postcode)',
    'train-offerbook(leaveat)',
    'police-inform(name)',
    'attraction-recommend(phone)',
    'hotel-recommend(address)',
    'train-offerbooked(arriveby)',
    'hotel-select(pricerange)',
    'taxi-inform(arriveby)',
    'train-offerbooked(departure)',
    'attraction-nooffer',
    'attraction-request(name)',
    'train-offerbook(arriveby)',
    'train-offerbooked(destination)',
    'booking-book',
    'attraction-select(type)',
    'train-inform(ref)',
    'restaurant-select(pricerange)',
    'hospital-request(department)',
    'hotel-select(area)',
    'hospital-inform(department)',
    'restaurant-select(area)',
    'restaurant-select(name)',
    'train-offerbooked(day)',
    'hotel-request(name)',
    'booking-nobook(name)',
    'booking-inform(bookday)',
    'attraction-request(entrancefee)',
    'hotel-select(name)',
    'restaurant-recommend(phone)',
    'restaurant-inform(ref)',
    'booking-nobook(bookday)',
    'booking-inform(bookpeople)',
    'booking-nobook(booktime)',
    'train-select(leaveat)',
    'restaurant-request(name)',
    'hotel-inform(ref)',
    'restaurant-recommend(postcode)',
    'hotel-select(stars)',
    'train-offerbook(destination)',
    'general-thank',
    'hotel-inform',
    'taxi-inform',
    'train-nooffer',
    'restaurant-inform',
    'hotel-recommend(postcode)',
    'train-offerbook(departure)',
    'train-nooffer(leaveat)',
    'train-offerbook(bookpeople)',
    'hotel-recommend(phone)',
    'booking-nobook(bookstay)',
    'hotel-select(choice)',
    'train-offerbooked',
    'hotel-nooffer(parking)',
    'attraction-select(area)',
    'booking-inform(booktime)',
    'attraction-inform',
    'attraction-select(name)',
    'train-offerbook(day)',
    'hotel-nooffer(internet)',
    'train-select(arriveby)',
    'attraction-select(entrancefee)',
    'booking-inform(bookstay)',
    'train-inform',
    'train-select(trainid)',
    'train-offerbook(price)',
    'train-nooffer(departure)',
    'booking-nobook(bookpeople)',
    'train-nooffer(destination)',
    'train-select(departure)',
    'train-select(day)',
    'restaurant-select(choice)',
    'restaurant-recommend(choice)',
    'train-nooffer(day)',
    'booking-nobook(ref)',
    'booking-inform(ref)',
    'attraction-inform(openhours)',
    'hotel-recommend',
    'attraction-recommend(choice)',
    'hotel-select(parking)',
    'train-select(destination)',
    'restaurant-recommend',
    'train-inform(bookpeople)',
    'hotel-select(internet)',
    'train-offerbooked(duration)',
    'hotel-recommend(choice)',
    'hotel-nooffer(name)',
    'taxi-request(bookpeople)',
    'train-offerbook(choice)',
    'train-offerbook(duration)',
    'attraction-recommend',
    'train-nooffer(arriveby)',
    'train-select(choice)',
    'restaurant-select(address)',
    'attraction-select(choice)',
    'hotel-nooffer(choice)',
    'attraction-nooffer(name)',
    'restaurant-nooffer(name)',
    'train-offerbook(ref)',
    'attraction-recommend(openhours)',
    'train-offerbooked(choice)',
    'booking-request',
    'train-nooffer(trainid)',
    'train-nooffer(choice)',
    'hotel-select(address)',
    'taxi-request',
    'train-select(bookpeople)',
    'attraction-select(phone)',
    'restaurant-nooffer(choice)',
    'hotel-select(phone)',
    'taxi-request(type)',
    'train-select(price)',
    'attraction-nooffer(choice)',
    'taxi-inform(choice)',
    'police-inform',
    'train-request',
    'taxi-request(bookday)',
    'attraction-request(phone)',
    'attraction-select(address)',
    'restaurant-request',
    'attraction-nooffer(address)',
]
